v = 'AMO FAZER EXERCICIO NO URI'

print('''<AMO FAZER EXERCICIO NO URI>
<    AMO FAZER EXERCICIO NO URI>
<AMO FAZER EXERCICIO >
<AMO FAZER EXERCICIO NO URI>
<AMO FAZER EXERCICIO NO URI    >
<AMO FAZER EXERCICIO NO URI>
<          AMO FAZER EXERCICIO >
<AMO FAZER EXERCICIO           >''')